---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-scope-cluster-agent
  namespace: monitoring
  labels:
    name: weave-scope-cluster-agent
    app: weave-scope
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: weave-scope-cluster-agent
      app: weave-scope
  template:
    metadata:
      labels:
        name: weave-scope-cluster-agent
        app: weave-scope
    spec:
      serviceAccountName: weave-scope
      containers:
        - name: scope-cluster-agent
          image: 'docker.io/weaveworks/scope:1.13.1'
          imagePullPolicy: IfNotPresent
          command:
            - /home/weave/scope
          args:
            - '--mode=probe'
            - '--probe-only'
            - '--weave=false'
            - '--probe.kubernetes.role=cluster'
            - '--probe.http.listen=:4041'
            - '--probe.publish.interval=4500ms'
            - '--probe.spy.interval=2s'
            - 'weave-scope-app.monitoring.svc.cluster.local.:80'
          ports:
            - containerPort: 4041
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 25m
              memory: 80Mi
