---
apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  namespace: monitoring
spec:
  selector:
    name: weave-scope-app
    app: weave-scope
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4040
